# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: About
    path: /about
    submenu:
      - label: Ice Stupa Project
        path: /about
      - label: SECMOL School
        path: /secmol
      - label: Ladakh Peoples' Alternative University
        path: /ladakh-peoples-alternative-university
      - label: Drikun Kagyud Monastery 
        path: /drikunkagyud-monastery
  - label: Photos
    path: /gallery
  - label: News
    path: /news
  - label: Contact
    path: /contact

footer:
  - label: About
    path: /about
  - label: Contact
    path: /contact
  - label: Donate
    class: donate-link
    path: /donate
